In [ ]:
import tensorflow as tf

url = 'https://storage.googleapis.com/download.tensorflow.org/example_images/YellowLabradorLooking_new.jpg'
file_name = 'YellowLabradorLooking_new.jpg'
path = tf.keras.utils.get_file(file_name, url)

In [ ]:
print(path)

In [ ]:
img = tf.io.read_file(path)
img = tf.image.decode_image(img, channels=3)
print(img.shape)
print(type(img))

In [ ]:
print(tf.math.reduce_min(img))
print(tf.math.reduce_max(img))

In [ ]:
img = tf.image.convert_image_dtype(img, tf.float32)
print(tf.math.reduce_min(img))
print(tf.math.reduce_max(img))

In [ ]:
# clip_by_value

In [ ]:
data = tf.random.normal((100, 100, 3))
print(tf.math.reduce_min(data))
print(tf.math.reduce_max(data))

In [ ]:
data = tf.clip_by_value(data, clip_value_min=0.0, clip_value_max=1.0)
print(tf.math.reduce_min(data))
print(tf.math.reduce_max(data))

In [ ]:
# tf.add_n

In [ ]:
result = tf.add_n([1, 2, 3])
print(result)

In [ ]:
# load image

In [ ]:
import PIL.Image
import tensorflow as tf
import matplotlib.pyplot as plt
import IPython.display as display
import numpy as np

In [ ]:
def load_img(path_to_img):
    img = tf.io.read_file(path_to_img)
    img = tf.image.decode_image(img, channels=3)
    img = tf.image.convert_image_dtype(img, tf.float32)  
    img = tf.image.resize(img, (422, 512))
    img = img[tf.newaxis, :]

    return img

In [ ]:
def imshow(image, title=None):
    if len(image.shape) > 3:
        image = tf.squeeze(image, axis=0)

    plt.imshow(image)
    if title:
        plt.title(title)

In [ ]:
url = 'https://storage.googleapis.com/download.tensorflow.org/example_images/YellowLabradorLooking_new.jpg'
file_name = 'YellowLabradorLooking_new.jpg'
path = tf.keras.utils.get_file(file_name, url)

image = load_img(path)
imshow(image, 'Content Image')

In [ ]:
def tensor_to_image(tensor):
    tensor = tensor*255
    tensor = np.array(tensor, dtype=np.uint8)
    if np.ndim(tensor)>3:
        assert tensor.shape[0] == 1
        tensor = tensor[0]
    return PIL.Image.fromarray(tensor)

In [ ]:
image = tf.random.uniform( (400, 400, 3), minval=0.0, maxval=1.5)
print(image.shape)
print(tf.math.reduce_min(image))
print(tf.math.reduce_max(image))

In [ ]:
def clip_0_1(image):
    return tf.clip_by_value(image, clip_value_min=0.0, clip_value_max=1.0)

image = clip_0_1(image)
print(tf.math.reduce_min(image))
print(tf.math.reduce_max(image))

In [ ]:
display.display(tensor_to_image(image))

# (1, 400, 400, 3)

In [ ]:
for _ in range(100):
    image = tf.random.uniform( (400,400,3), minval=0.0, maxval=1.5)
    image = clip_0_1(image)    
    
    display.clear_output(wait=True)
    display.display(tensor_to_image(image))

# Einsum

In [61]:
# vector
import tensorflow as tf

u = tf.convert_to_tensor([3, 2, 4, 1], dtype=tf.int64)
v = tf.convert_to_tensor([2, 1, 0, 3], dtype=tf.int64)

print(u)
print(v)

tf.Tensor([3 2 4 1], shape=(4,), dtype=int64)
tf.Tensor([2 1 0 3], shape=(4,), dtype=int64)


In [63]:
# matrix
A = tf.convert_to_tensor([[0, 2, 1],
                          [3, 1, 4]], dtype=tf.int64)
B = tf.convert_to_tensor([[2, 5],
                          [0, 1],
                          [3, 4]], dtype=tf.int64)

print(A)
print(B)

tf.Tensor(
[[0 2 1]
 [3 1 4]], shape=(2, 3), dtype=int64)
tf.Tensor(
[[2 5]
 [0 1]
 [3 4]], shape=(3, 2), dtype=int64)


In [64]:
# Matrix multiplication
C = tf.einsum('ij,jk->ik', A, B)
print(C)

tf.Tensor(
[[ 3  6]
 [18 32]], shape=(2, 2), dtype=int64)


In [65]:
import tensorflow as tf

u = tf.convert_to_tensor([3, 2, 4, 1])
v = tf.convert_to_tensor([2, 1, 0, 3])

# dot product
r = tf.einsum('i,i->', u, v)
print(r)

tf.Tensor(11, shape=(), dtype=int32)


In [67]:
import tensorflow as tf

u = tf.convert_to_tensor([3, 2, 4, 1])
v = tf.convert_to_tensor([2, 1, 0, 3])

# outer product
r = tf.einsum('i,j->ij', u, v)
print(r)

tf.Tensor(
[[ 6  3  0  9]
 [ 4  2  0  6]
 [ 8  4  0 12]
 [ 2  1  0  3]], shape=(4, 4), dtype=int32)


In [68]:
import tensorflow as tf

# matrix
A = tf.convert_to_tensor([[0, 2, 1],
                          [3, 1, 4]]))

# transpose
r = tf.einsum('ij->ji', A)
print(r)

tf.Tensor(
[[0 3]
 [2 1]
 [1 4]], shape=(3, 2), dtype=int32)


In [71]:
import tensorflow as tf

# matrix
A = tf.convert_to_tensor([[5, 2, 1],
                          [3, 1, 6],
                          [2, 4, 3]])

# diagonal
r = tf.einsum('ii->i', A)
print(r)

tf.Tensor([5 1 3], shape=(3,), dtype=int32)


In [73]:
import tensorflow as tf

# matrix
A = tf.convert_to_tensor([[5, 2, 1],
                          [3, 1, 6],
                          [2, 4, 3]])

# trace
r = tf.einsum('ii->', A)
print(r)

tf.Tensor(9, shape=(), dtype=int32)


In [82]:
import tensorflow as tf

# matrices
A = tf.convert_to_tensor([[[3, 0, 1],
                           [4, 2, 3]],
                          [[1, 0, 2],
                           [3, 2, 1]]], dtype=tf.int64)
B = tf.convert_to_tensor([[[1, 0],
                           [2, 2],
                           [1, 3]],
                          [[3, 1],
                           [0, 2],
                           [1, 3]]], dtype=tf.int64)

print(A[0])
print(A[1])
print()
print(B[0])
print(B[1])

tf.Tensor(
[[3 0 1]
 [4 2 3]], shape=(2, 3), dtype=int64)
tf.Tensor(
[[1 0 2]
 [3 2 1]], shape=(2, 3), dtype=int64)

tf.Tensor(
[[1 0]
 [2 2]
 [1 3]], shape=(3, 2), dtype=int64)
tf.Tensor(
[[3 1]
 [0 2]
 [1 3]], shape=(3, 2), dtype=int64)


In [83]:
C = tf.einsum('bij,bjk->bik', A, B)
print(C[0])
print(C[1])

tf.Tensor(
[[ 4  3]
 [11 13]], shape=(2, 2), dtype=int64)
tf.Tensor(
[[ 5  7]
 [10 10]], shape=(2, 2), dtype=int64)


In [84]:
import tensorflow as tf

# matrices
A = tf.convert_to_tensor([[3, 0, 1],
                          [4, 2, 3]])
B = tf.convert_to_tensor([[1, 0, 2],
                           [3, 2, 1]])

# element-wise multiplication
C = tf.einsum('ij,ij->ij', A, B)
print(C)

tf.Tensor(
[[ 3  0  2]
 [12  4  3]], shape=(2, 3), dtype=int32)


In [2]:
import tensorflow as tf

# matrices
A = tf.convert_to_tensor([[3, 0, 1],
                          [4, 2, 3]])

# element-wise multiplication
C = tf.einsum('ij,kj->ik', A, A)
print(C)

tf.Tensor(
[[10 15]
 [15 29]], shape=(2, 2), dtype=int32)


In [56]:
# vector

import tensorflow as tf

u = tf.convert_to_tensor([3, 2, 4, 1], dtype=tf.int64)
v = tf.convert_to_tensor([2, 1, 0, 3], dtype=tf.int64)

print(u)
print(v)

tf.Tensor([3 2 4 1], shape=(4,), dtype=int64)
tf.Tensor([2 1 0 3], shape=(4,), dtype=int64)


In [57]:
e = tf.einsum('i,i->i', u, v)
print(e)

tf.Tensor([6 2 0 3], shape=(4,), dtype=int64)


In [58]:
e = tf.einsum('i,j->i', u, v)
print(e)

tf.Tensor([18 12 24  6], shape=(4,), dtype=int64)


In [59]:
e = tf.einsum('i,j->j', u, v)
print(e)

tf.Tensor([20 10  0 30], shape=(4,), dtype=int64)


In [60]:
e = tf.einsum('i,i->', u, v)
print(e)

tf.Tensor(11, shape=(), dtype=int64)


In [26]:
# matrix

A = tf.random.uniform(shape=[2, 3], minval=0, maxval=8, dtype=tf.int64)
B = tf.random.uniform(shape=[3, 2], minval=0, maxval=8, dtype=tf.int64)
print(A)
print(B)

tf.Tensor(
[[0 2 7]
 [7 1 4]], shape=(2, 3), dtype=int64)
tf.Tensor(
[[5 7]
 [4 1]
 [5 6]], shape=(3, 2), dtype=int64)


In [38]:
A = tf.convert_to_tensor([[0, 2, 1],
                          [3, 1, 4]], dtype=tf.int64)
B = tf.convert_to_tensor([[3, 1],
                          [0, 2],
                          [1, 4]], dtype=tf.int64)

print(A)
print(B)

tf.Tensor(
[[0 2 1]
 [3 1 4]], shape=(2, 3), dtype=int64)
tf.Tensor(
[[3 1]
 [0 2]
 [1 4]], shape=(3, 2), dtype=int64)


In [39]:
r = tf.linalg.matmul(A, B)
print(r)

tf.Tensor(
[[ 1  8]
 [13 21]], shape=(2, 2), dtype=int64)


In [40]:
e = tf.einsum('ij,ji->i', A, B)
print(e)

tf.Tensor([ 1 21], shape=(2,), dtype=int64)


In [41]:
e = tf.einsum('ij,ji->j', A, B)
print(e)

tf.Tensor([ 3  2 17], shape=(3,), dtype=int64)


In [42]:
e = tf.einsum('ij,ji->ij', A, B)
print(e)

tf.Tensor(
[[ 0  0  1]
 [ 3  2 16]], shape=(2, 3), dtype=int64)


In [43]:
e = tf.einsum('ik,kj->ij', A, B)
print(e)

tf.Tensor(
[[ 1  8]
 [13 21]], shape=(2, 2), dtype=int64)


In [3]:
m0 = tf.random.uniform(shape=[2, 3], minval=0, maxval=5, dtype=tf.int64)
m1 = tf.random.uniform(shape=[3, 1], minval=0, maxval=5, dtype=tf.int64)
#e = tf.einsum('ij,jk->ik', m0, m1)

# output[i,k] = sum_j m0[i,j] * m1[j, k]
print(m0)
print(m1)
#print(e)

tf.Tensor(
[[2 1 2]
 [3 1 4]], shape=(2, 3), dtype=int64)
tf.Tensor(
[[2]
 [3]
 [0]], shape=(3, 1), dtype=int64)


In [7]:
e = tf.einsum('ij,jk->ik', m0, m1)
print(e)

tf.Tensor(
[[13]
 [10]], shape=(2, 1), dtype=int64)


In [9]:
data = tf.random.uniform(shape=[1, 26, 32, 512], minval=0, maxval=5, dtype=tf.int64)
print(data.shape)

(1, 26, 32, 512)


In [10]:
data = tf.random.uniform(shape=[1, 1, 2, 3], minval=0, maxval=5, dtype=tf.int64)
e = tf.einsum('bijc,bijd->bcd', data, data)

print(data[:,:,:,0])
print(data[:,:,:,1])
print(data[:,:,:,2])
print(e)

tf.Tensor([[[2 0]]], shape=(1, 1, 2), dtype=int64)
tf.Tensor([[[2 0]]], shape=(1, 1, 2), dtype=int64)
tf.Tensor([[[1 0]]], shape=(1, 1, 2), dtype=int64)
tf.Tensor(
[[[4 4 2]
  [4 4 2]
  [2 2 1]]], shape=(1, 3, 3), dtype=int64)


## gram matrix

In [17]:
import numpy as np

data = np.array([[4, 0, 3, 1],
                 [3, 0, 1, 2],
                 [4, 5, 0, 3]])
print(data)

[[4 0 3 1]
 [3 0 1 2]
 [4 5 0 3]]


In [18]:
gram = data @ data.T
print(gram)

[[26 17 19]
 [17 14 18]
 [19 18 50]]


In [19]:
data.T

array([[4, 3, 4],
       [0, 0, 5],
       [3, 1, 0],
       [1, 2, 3]])