In [17]:
import tensorflow as tf
import numpy as np

x = tf.keras.Input(shape=[4, 3])
layer  = tf.keras.layers.MultiHeadAttention(num_heads=1, key_dim=2, use_bias=False)

output_tensor = layer(x, x)
print(output_tensor.shape)

(None, 4, 3)


In [12]:
weights = layer.get_weights()
print(len(weights))

4


In [13]:
print(weights[0].shape)
print(weights[1].shape)
print(weights[2].shape)
print(weights[3].shape)

(3, 1, 2)
(3, 1, 2)
(3, 1, 2)
(1, 2, 3)


In [14]:
print(weights[0])
print(weights[1])
print(weights[2])
print(weights[3])

[[[-0.12396264  0.7478199 ]]

 [[-0.068156   -0.21653873]]

 [[-0.53729546  0.7586386 ]]]
[[[ 0.31700003 -0.14360964]]

 [[ 0.01657248  0.15539545]]

 [[ 0.794294   -0.756286  ]]]
[[[ 0.50961876  0.5313524 ]]

 [[-0.09354848  0.17850602]]

 [[ 0.77781975 -0.711644  ]]]
[[[ 0.12971807 -0.16721696  0.6816946 ]
  [ 0.9444294   0.3945315   0.16186547]]]


In [18]:
q = np.array([[[ 0.4,  0.3 ]],
              [[-0.1, -0.1]],
              [[ 0.2, -0.1]]])
k = np.array([[[ 0.1,  0.2 ]],
              [[-0.3, -0.4]],
              [[-0.1,  0.2]]])
v = np.array([[[-0.2,  0.1 ]],
              [[-0.4,  0.2]],
              [[ 0.4, -0.6]]])
o = np.array([[[ 0.1, -0.1,  0.6 ],
               [ 0.9,  0.3,  0.1 ]]])

In [19]:
layer.set_weights([q, k, v, o])

In [21]:
weights = layer.get_weights()
print(weights[0])
print(weights[1])
print(weights[2])
print(weights[3])

[[[ 0.4  0.3]]

 [[-0.1 -0.1]]

 [[ 0.2 -0.1]]]
[[[ 0.1  0.2]]

 [[-0.3 -0.4]]

 [[-0.1  0.2]]]
[[[-0.2  0.1]]

 [[-0.4  0.2]]

 [[ 0.4 -0.6]]]
[[[ 0.1 -0.1  0.6]
  [ 0.9  0.3  0.1]]]


In [22]:
data = np.array([[1., 2., 1., 0.],
                 [4., 1., 3., 5.],
                 [3., 1., 3., 3.]])
data = data.reshape((1, 4, 3))
print(data.shape)
print(data)

(1, 4, 3)
[[[1. 2. 1.]
  [0. 4. 1.]
  [3. 5. 3.]
  [1. 3. 3.]]]


In [23]:
output = layer(data, data)
print(output[0])

tf.Tensor(
[[-0.4142852  -0.02864021 -0.52945733]
 [-0.38586974 -0.0066171  -0.58173496]
 [-0.39637557 -0.03216458 -0.48553446]
 [-0.38704437 -0.01838657 -0.53161293]], shape=(4, 3), dtype=float32)
